language: objective-c
osx_image: xcode7
xcode_workspace: saml-ios-swift.xcworkspace
xcode_scheme: saml-ios-swift
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master