language: objective-c
osx_image: xcode7.3
xcode_workspace: saml-ios-swift.xcworkspace
xcode_scheme: saml-ios-swift
xcode_sdk: iphonesimulator

before_install:
  - pod repo update

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master